### ISSUE TITLE
Trained models are expired.

### ISSUE THREAD

**Issue by liguopeng0923** [shiyujiao/IBL#6]
[Trained models are expired](https://github.com/shiyujiao/IBL/assets/61257834/a4ea88d2-938a-4e6d-a388-02113abf187e).

Are the results in [this table](https://github.com/shiyujiao/IBL/assets/61257834/1eeff983-8a1e-4987-bc64-8adc7c69bb6c)  based on corrected GT or the center of aerial image?

**Comment by wappints** [comment]
Bump

**Comment by YujiaoShi** [comment]
updated
